name: Build
on:
  push:
    branches:
      - main
jobs:
  app:
    name: 'Build & Test App'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'NPM Install'
        uses: ./.github/actions/setup-node
        with:
          npm-token: ${{ secrets.NPM_PACKAGES_TOKEN }}
      - name: 'Build'
        run: npm run build
      - name: 'Test'
        run: npm test
      - name: 'Upload Build'
        uses: actions/upload-artifact@v4
        with:
          name: 'build'
          path: build/
      - name: 'Upload Generated'
        uses: actions/upload-artifact@v4
        with:
          name: 'generated'
          path: generated/

  translate:
    name: 'Translate Terraform'
    needs: app
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'NPM Install'
        uses: ./.github/actions/setup-node
        with:
          npm-token: ${{ secrets.NPM_PACKAGES_TOKEN }}
      - name: 'Download Artifacts'
        uses: actions/download-artifact@v4
      - name: 'Terraform Translate'
        run: npm run translate
      - name: 'Upload Stack'
        uses: actions/upload-artifact@v4
        with:
          name: 'cdktf.out'
          path: cdktf.out/
  sdk:
    name: 'Build & Publish SDK'
    needs: app
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'NPM Install'
        uses: ./.github/actions/setup-node
        with:
          working-directory: 'sdk'
          npm-token: ${{ secrets.NPM_PACKAGES_TOKEN }}
      - name: 'Download Artifacts'
        uses: actions/download-artifact@v4
      - name: 'Build SDK'
        working-directory: 'sdk'
        run: |
          npm --no-git-tag-version version 1.0.${{ github.run_number }}
          npm run build
      - name: 'Package SDK'
        working-directory: 'sdk'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
