namespace = "<%= namespace %>"
name = "<%= name %>"
environment = "<%= environment.name %>"
domain = "<%= environment.domain %>"
code_s3_bucket = "<%= namespace %>-deploys-us-east-1-<%= environment.name %>"
