name: Check Pull Request
on:
  pull_request:
    branches:
      - main
jobs:

  generate:
    uses: gitboard-io/workflows/.github/workflows/generate.yml@main
    secrets:
      npm-token: ${{secrets.NPM_PACKAGES_TOKEN}}

  build:
    uses: gitboard-io/workflows/.github/workflows/build.yml@main
    secrets:
      npm-token: ${{secrets.NPM_PACKAGES_TOKEN}}

  test:
    needs: generate
    uses: gitboard-io/workflows/.github/workflows/test.yml@main
    secrets:
      npm-token: ${{secrets.NPM_PACKAGES_TOKEN}}

  translate:
    needs: generate
    uses: gitboard-io/workflows/.github/workflows/kloudformation-translate.yml@main
    with: { name: '<%= name %>-service' }
    secrets:
      npm-token: ${{secrets.NPM_PACKAGES_TOKEN}}

  sdk:
    needs: ['build', 'test']
    uses: gitboard-io/workflows/.github/workflows/sdk-build.yml@main
    secrets:
      npm-token: ${{secrets.NPM_PACKAGES_TOKEN}}
