name: Build & Publish

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: NPM Version
        run: |
          npm --no-git-tag-version version 1.0.${{ github.run_number }}
          echo "## NPM Version" >> $GITHUB_STEP_SUMMARY
          echo "\`npm install -S @hexlabs/schema-api-ts@1.0.${{ github.run_number }}\`" >> $GITHUB_STEP_SUMMARY

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Production Build
        run: npm run build

      - name: Package
        run: npm pack

      - name: Publish NPM package
        if: github.ref == 'refs/heads/main'
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm publish --access public
